export const SLIDER_DATA = [
  {
    id: 1,
    title: "SENTINELS",
    description: "A global peacekeeping force for the public good.",
    svg: "/logos/1.svg",
    coverImage: "/main-images/1-cover.png",
    inImage: "/main-images/1-in.png",
  },
  {
    id: 2,
    title: "THE CELESTE GROUP",
    description: "An elite organization of strategic operatives.",
    svg: "/logos/2.svg",
    coverImage: "/main-images/2-cover.png",
    inImage: "/main-images/2-in.png",
  },
  {
    id: 3,
    title: "OX898",
    description: "A rag-tag group of dissidents and extremists, with the cause of freedom of information and equality.",
    svg: "/logos/3.svg",
    coverImage: "/main-images/3-cover.png",
    inImage: "/main-images/3-in.png",
  },
  {
    id: 4,
    title: "PATRIOTS DIVISION",
    description: "An American security company specializing in arms manufacturing.",
    svg: "/logos/4.svg",
    coverImage: "/main-images/4-cover.png",
    inImage: "/main-images/4-in.png",
  },
  {
    id: 5,
    title: "LEBENSKRAFT ARMORERS",
    description: "A global materials science firm that develops next-generation robots.",
    svg: "/logos/5.svg",
    coverImage: "/main-images/5-cover.png",
    inImage: "/main-images/5-in.png",
  },
  {
    id: 6,
    title: "SANZU BIOMEDICAL",
    description: "A triumvirate of leading organizations in technology, science, and government.",
    svg: "/logos/6.svg",
    coverImage: "/main-images/6-cover.png",
    inImage: "/main-images/6-in.png",
  },
  {
    id: 7,
    title: "JUNPEI LIGHT & POWER",
    description: "Asia's largest energy multinational and specialist in fusion technology.",
    svg: "/logos/7.svg",
    coverImage: "/main-images/7-cover.png",
    inImage: "/main-images/7-in.png",
  },
  {
    id: 8,
    title: "DEADEYE ENFORCERS",
    description: "A global network composed of ex-NATO members.",
    svg: "/logos/8.svg",
    coverImage: "/main-images/8-cover.png",
    inImage: "/main-images/8-in.png",
  },
  {
    id: 9,
    title: "THE ORDER",
    description: "Maintaining balance through structure.",
    svg: "/logos/9.svg",
    coverImage: "/main-images/9-cover.png",
    inImage: "/main-images/9-in.png",
  },
];